### ISSUE TITLE
Empty space on 1080 displays

### ISSUE THREAD

**Issue by MasterGeekMX** [dfaust/plasma-applet-places-widget#6]
Since plasma 5.15 I noticed that if the widget is placed on a panel on a 1920x1080 screen, a blank space is visible on the bottom with the height of 4 entries (they even get resalted on mouse hover). I also have a second moinot at 1366x768 and that does not happen. Its also not present if I place the widget in the desktop.

Behavior sighted on KDE Neon and Arch.

![imagen](https://user-images.githubusercontent.com/10291989/62835353-21e15600-bc1d-11e9-9584-4686fdaa6588.png)

![imagen](https://user-images.githubusercontent.com/10291989/62835460-6f11f780-bc1e-11e9-8793-961237674608.png)

**Comment by dfaust** [comment]
I don't have many ideas here, could you play around with the settings a little bit, maybe that will reveal something.

**Comment by MasterGeekMX** [comment]
I played with the options. nothing.

Funny enough I had a problem with my plasma setup (temoid was causing plasmashell to crash), so I went to the .config/plasma-org.kde.{something something applet setup}, commented the lines that matched temoid, resarted the system and the issue was gone. And I'm pretty sure anything in KDE set was updated

**Comment by stevepet** [comment]
I am seeing the same thing with Plasma 5.20.4 but I am not using the same resolution as the OP (2560x1440). It does not happen on first install for me. I must restart the widget through a system reboot to see the issue. I can uninstall the widget and re-install and it will be fine until reboot.
Thanks for the widget and for looking into this. :-)

**Comment by stevepet** [comment]
I was able to filter out the blanks in the ListView with the following change:

Edit the following file:  ~/.local/share/plasma/plasmoids/org.kde.placesWidget/contents/ui/FullRepresentation.qml

Add the following before the "PlasmaExtras.ScrollArea" code block:

PlasmaCore.SortFilterModel {
     id: placesBlankFilterModel
     sourceModel: placesSearchesFilterModel
     filterRole: ''
     filterRegExp: '^(?!search).+'

Change the following in the "PlasmaExtras.ScrollArea" code block:

model: placesSearchesFilterModel ==> model: placesBlankFilterModel

**Comment by dfaust** [comment]
While I still don't know exactly what happens here, the code by @stevepet gave me the right idea for a fix. Thank you!
I have release version 1.4 with the fix. Let me know if the bug still persists.
